### ISSUE TITLE
"CIDR Subnet Mask Calculator" (Website): some subnet masks not working correct

### ISSUE THREAD

**Issue by ghost** [salieri/IPSubnetCalculator#9]
The calculation at "CIDR Subnet Mask Calculator" on the website https://salieri.github.io/IPSubnetCalculator/ is working for the common, top listed subnet masks ("/24", "/16", "/8") but not for all values listed after "----------------------".

If you chose e.g. "/24" from the top of the list you get the correct subnet mask 255.255.255.0.
If you chose the second list entry for "/24" (down in the list) you get subnet mask 240.0.0.0.

The problem is at all subnet masks greater "/20" because of wrong "value" for the options. The values start again with "1" (for "/21") but should be "21" and so on.
See https://github.com/salieri/IPSubnetCalculator/blob/61f0dd7ceacbf64f2551e584bd6cdb83164b273d/index.html#L87

**Comment by salieri** [comment]
Fixed!
